### ISSUE TITLE
Resend verification request

### ISSUE THREAD

**Issue by DarkInsight85** [Nexmo/verify-ios-sdk#3]
I notice that there is no "resendVerification" method, may I know how should I implement this feature? I have tried calling + (void)cancelVerificationWithBlock: and + (void)getVerifiedUserWithCountryCode:(NSString \* __nullable)countryCode phoneNumber:(NSString \* __nonnull)phoneNumber verifyInProgressBlock:(void (^ __nonnull)(void))onVerifyInProgress userVerifiedBlock:(void (^ __nonnull)(void))onUserVerified errorBlock:(void (^ __nonnull)(enum VerifyError))onError; in the completion block. However the cancelVerification seems to always return error.

**Comment by dozzman** [comment]
Hi DarkInsight85,

You're correct, there is no 'resendVerification' method. I assume by 'resendVerification' you mean a function which simply attempts to send the verification SMS again, with the same pin code, whilst not restarting the verification request.

This exact solution is currently unavailable, but there are a few ways you can achieve a similar result to what you want.
1. **Trigger Next Event**
   the VerifyClient `+ (void)triggerNextEventWithBlock:(void (^)(NSError __nullable))completionBlock` function will trigger the next stage of the verify workflow earlier than the default time. Therefore if the verify workflow looks like this [SMS] -> TTS -> TTS, and you call `triggerNextEvent` the TTS stage will be executed... SMS -> [TTS] -> TTS.
2. **Cancel and Re-Verify**
   You mentioned you have already tried this method however it always fails with an error. The reason may be because you cannot cancel a verification within 30 seconds of it being initialised. Therefore if a 30 second window is appropriate for your resendVerification use case, you can take this timing into consideration whilst implementing your application.
   
   One thing to consider is that you will be performing a _new_ verification, which means that the previous pin code will become invalid. Therefore you may encounter the situation where your user has received the pin code already and you restart the verification, resulting in the user receiving another message with a _different_ pin code. This can be quite confusing.

In my opinion I would simply stick with the `triggerNextEvent` call, since it is our tried and tested method, with a high conversion rate. However the current default timings for moving onto the next verification stage provide a good balance between ensuring the user performs a successful verification and providing a pleasant user experience.
