### ISSUE TITLE
Swift 2.3 issues

### ISSUE THREAD

**Issue by sschizas** [Nexmo/verify-ios-sdk#6]
In HttpRequestBuilder.swift in lines 116 and 129:
- urlString = self.url.absoluteString

i get the following warning: Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?

I think you should check it out as it's optional and in case absoluteString is nil the proper handling should be in place

**Comment by sschizas** [comment]
@dozzman update on this one?

**Comment by anton-ogarkov** [comment]
@dozzman experiencing the same problem. Prior to this I had to set the `Use Legacy Swift Language Version` to `YES` in order to avoid the `VerifyIosSdk` compilation problem

`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

**Comment by shams-ahmed** [comment]
```
Apple: “Xcode 8.2 is the last release that will support Swift 2.3. Please migrate your projects to Swift 2.3 code to Swift 3”
```

We will not official support or maintain swift 2.3 version on verify
